# Generated by Django 5.2.10 on 2026-01-28 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gmail_message_id", models.CharField(db_index=True, max_length=255)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("sender_email", models.EmailField(max_length=254)),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=500)),
                ("received_date", models.DateTimeField(db_index=True)),
                ("raw_html", models.TextField(blank=True)),
                ("snippet", models.TextField(blank=True)),
                ("is_processed", models.BooleanField(db_index=True, default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("link_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "newsletter email",
                "verbose_name_plural": "newsletter emails",
                "ordering": ["-received_date"],
                "unique_together": {("user", "gmail_message_id")},
            },
        ),
        migrations.CreateModel(
            name="ExtractedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_url", models.URLField(max_length=2000)),
                ("canonical_url", models.URLField(db_index=True, max_length=2000)),
                ("anchor_text", models.TextField(blank=True)),
                ("surrounding_text", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid Article"),
                            ("invalid", "Invalid"),
                            ("duplicate", "Duplicate"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_valid_article", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_links",
                        to="articles.article",
                    ),
                ),
                (
                    "newsletter_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_links",
                        to="emails.newsletteremail",
                    ),
                ),
            ],
            options={
                "verbose_name": "extracted link",
                "verbose_name_plural": "extracted links",
                "ordering": ["-created_at"],
            },
        ),
    ]
