# Generated by Django 5.2.10 on 2026-01-28 21:02

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "canonical_url",
                    models.URLField(db_index=True, max_length=2000, unique=True),
                ),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("publication", models.CharField(blank=True, max_length=255)),
                (
                    "publication_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("content_text", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True)),
                ("excerpt", models.TextField(blank=True)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=768, null=True),
                ),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("similarity_to_cluster", models.FloatField(blank=True, null=True)),
                (
                    "scrape_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scrape_error", models.TextField(blank=True)),
                ("scrape_attempts", models.IntegerField(default=0)),
                ("last_scrape_at", models.DateTimeField(blank=True, null=True)),
                ("og_image", models.URLField(blank=True, max_length=2000)),
                ("language", models.CharField(blank=True, default="en", max_length=10)),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ["-publication_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleDuplicate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("similarity_score", models.FloatField()),
            ],
            options={
                "verbose_name": "article duplicate",
                "verbose_name_plural": "article duplicates",
            },
        ),
    ]
