# Generated by Django 5.2.10 on 2026-01-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
        ("clusters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topic_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="clusters.topiccluster",
            ),
        ),
        migrations.AddField(
            model_name="articleduplicate",
            name="duplicate_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicated_by",
                to="articles.article",
            ),
        ),
        migrations.AddField(
            model_name="articleduplicate",
            name="primary_article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_references",
                to="articles.article",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["scrape_status", "scrape_attempts"],
                name="articles_ar_scrape__781d3b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleduplicate",
            unique_together={("primary_article", "duplicate_article")},
        ),
    ]
