# Generated by Django 5.2.10 on 2026-01-28 21:02

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "centroid_embedding",
                    pgvector.django.VectorField(blank=True, dimensions=768, null=True),
                ),
                ("article_count", models.IntegerField(default=0)),
                ("priority_score", models.FloatField(default=0.0)),
                ("master_summary", models.TextField(blank=True)),
                ("summary_generated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_article_added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "primary_article",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_for_clusters",
                        to="articles.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "topic cluster",
                "verbose_name_plural": "topic clusters",
                "ordering": ["-priority_score", "-article_count"],
            },
        ),
        migrations.CreateModel(
            name="ClusterMerge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
                ("articles_moved", models.IntegerField(default=0)),
                (
                    "source_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_from",
                        to="clusters.topiccluster",
                    ),
                ),
                (
                    "target_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merged_into",
                        to="clusters.topiccluster",
                    ),
                ),
            ],
            options={
                "verbose_name": "cluster merge",
                "verbose_name_plural": "cluster merges",
            },
        ),
    ]
